### ISSUE TITLE
Add support for solarized darcula?

### ISSUE THREAD

**Issue by pbiggar** [sellout/emacs-color-theme-solarized#101]
Here's the [homepage](https://github.com/rickhanlonii/Solarized-Darcula), and here's the [iterm file](https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/schemes/Solarized%20Darcula.itermcolors).

I tried to figure out how to make this work, but was a bit overwhelmed.

**Comment by sellout** [comment]
I just took a quick look and it seems like this theme combines colors from two other themes? I’m not really interested in managing any other themes myself, but it may very well be that the code in this repo would be a good basis for it. Feel free to fork, and I can help with specific questions.

Also, this repo was recently overhauled and that may make reuse a bit easier.
