### ISSUE TITLE
Add support for Powerline

### ISSUE THREAD

**Issue by dblarons** [sellout/emacs-color-theme-solarized#115]
Please add support for one of Emacs' most popular ports of powerline.

https://github.com/milkypostman/powerline

**Comment by arielschiavoni** [comment]
+1 to support for powerline :-)

**Comment by sellout** [comment]
Ok, I found three bugs in Powerline’s handling of faces and I plan to submit a PR for it:

1. when looking up colors, it doesn’t pay attention to face inheritance, so it may not get a color value;
2. it doesn’t pay attention to `:inverse-video`, so if a mode-line is inverted (like Solarized’s) Powerline will grab the foreground color by accident; and
3. when creating the XPM files for transitions, it doesn’t adjust for sRGB, so the colors are slightly off (at least, I _think_ that’s what’s happening).

The first two seem pretty straightforward. I might just submit those first. I imagine the last one probably only affects Mac users, but I’m just guessing.

**Comment by sellout** [comment]
I see milkypostman/powerline#22 is the same issue. I have a fix for the first two points that I should get submitted today.

(As well as Solarized-friendly settings for the Powerline faces.)

**Comment by sellout** [comment]
Point 3 is covered by milkypostman/powerline#54, so I’ll commit some Solarized Powerline faces and consider this closed (but I am happy to take suggestions of other combinations for the Powerline display – not particularly excited with what I came up with, but at least everything is readable).

**Comment by sellout** [comment]
(But Powerline won’t look right yet unless you pull from git or wait for the next version to hit MELPA.)

**Comment by sellout** [comment]
Here is what Powerline looks like for me now, BTW: 

![cursor_and__eshell___ ___163_x_77__and__slamdata](https://cloud.githubusercontent.com/assets/33031/7373727/655a761a-ed8b-11e4-8e94-e86338e79e81.png)

The bottom mode-line is active, and I’m using UTF-8 separators (#x25ba / #x25c4) since XPM images on OS X don’t (yet?) handle the sRGB colorspace properly.
