### ISSUE TITLE
`font-lock-label-face` not defined

### ISSUE THREAD

**Issue by chachi** [sellout/emacs-color-theme-solarized#116]
This is the face used in C++ for namespaces or class labels before `::`.

I'm not particular to any color, but I wanted to see if this was an intentional omission before submitting a PR.

**Comment by sellout** [comment]
I’m on emacs 24.4 and I don’t see a `font-lock-label-face`. Could you `M-x describe-face font-lock-label-face` and let me know where it says it’s defined? Thanks.

**Comment by chachi** [comment]
Oops, my apologies. After further investigation, it seems I just made that face up (based on some old SO post).
