### ISSUE TITLE
Magit highlighting broken

### ISSUE THREAD

**Issue by prunes** [sellout/emacs-color-theme-solarized#126]
I think this [1] commit tried to fix the issue but highlighting in magit is still broken for me. The face of the hightlighted text is the same color as the background.

     [1] https://github.com/sellout/emacs-color-theme-solarized/pull/124

**Comment by sellout** [comment]
I don’t seem to have a `magit-item-highlight` face on my system, and `secondary-selection` is reasonably defined (should be base0 on base02).

Could you update to the latest from master and see if you’re still seeing this issue? Thanks.

**Comment by sellout** [comment]
Sorry – I do have `magit-item-highlight` and it’s defined as you said (magit just hadn’t been loaded in my session). However, it looks fine to me as does the definition of `secondary-selection`, so I’m still no help.

**Comment by prunes** [comment]
I switched to the Cocoa emacs and everything is gravy now.

**Comment by sellout** [comment]
Great! Thanks for responding.
