### ISSUE TITLE
"Symbol's value as variable is void" when loading *Custom Theme* buffer

### ISSUE THREAD

**Issue by mattduck** [sellout/emacs-color-theme-solarized#132]
Can reproduce by:

- M-x customize-themes
- Move cursor to a Solarized line and do M-x custom-describe-theme
- Press RET on the "Customize" button.

It hits the error on the background-mode variable, and the rest of the \*Custom Theme\* buffer is not rendered. Fix submitted in #131.

**Comment by sellout** [comment]
This seems to be fixed after my latest big changes. Please re-open if it’s not.
