### ISSUE TITLE
Solarized-light in iTerm2

### ISSUE THREAD

**Issue by ephexeve** [sellout/emacs-color-theme-solarized#155]
I am having difficulties to get Solarized-dark working in iTerm2.
My Terminal type is set to ```xterm-256color``` and I have solarized.iterm loaded as my iTerm2 theme.
In my ```.emacs``` I have:

```
; load solarized-theme
; https://github.com/sellout/emacs-color-theme-solarized
(add-to-list 'custom-theme-load-path "~/.emacs.d/solarized")
(load-theme 'solarized t)
```

This is the result -> https://i.imgur.com/tUwcuDQ.png

If I try M-x -> load-theme -> solarized-dark, I get the same result. 

I tried setting my Terminal type to ```xterm-new```, though it "works" I still see some solarized-light in a few parts, like so -> http://i.imgur.com/kHUe95m.png 

Any idea of what to do?

Thanks

**Comment by sellout** [comment]
The `solarized-light` and `solarized-dark` themes are deprecated (and I should probably get rid of them to eliminate confusion like this). Now there is only a single `solarized` theme that uses dark/light variants based on the frame’s `background-mode` (so you can mix dark and light frames in the same Emacs instance).

The hook I use to set this up (I use `light` for GUI frames and `dark` for term frames) is in the README: https://github.com/sellout/emacs-color-theme-solarized#all-versions. It could actually be a bit simpler for your case, but I don’t know any way to set default terminal parameters, so you need to make sure your `background-mode` is set to `dark` for each new terminal *shrug*. Let me know if that helps.

**Comment by ephexeve** [comment]
Awesome, I've seen you did a new push on the README.md, thanks for that.
I kinda fixed it by following the README.md, but only by adding:

```
(add-to-list 'custom-theme-load-path "~/.emacs.d/solarized")
(setq frame-background-mode 'dark)
(load-theme 'solarized-dark t)
```

This is what I got now -> https://i.imgur.com/nOF426q.png 
As you can see in the powerline, it seems that some words are very difficult to read. Any idea what this could be? Perhaps I missed something?

**Comment by sellout** [comment]
Powerline badness is a known issue: #115. I’ll look at that again.

I’m going to close this, but reopen if you feel it’s not resolved.

**Comment by ephexeve** [comment]
It's working perfect. 
This is what I added to my .emacs:
```
; load solarized-theme
; https://github.com/sellout/emacs-color-theme-solarized
(setq frame-background-mode 'dark)
(load-theme 'solarized-dark t)
```
Then;
```
; powerline
(setq sml/no-confirm-load-theme t)
(setq sml/theme 'respectful)
(sml/setup)
```

Apparently ```sml/theme solarized-dark``` doesn't work properly, instead, ```respectful``` seems to work quite fine. 

Cheers.
