### ISSUE TITLE
Color mismatch on Haskell sources

### ISSUE THREAD

**Issue by geraldus** [sellout/emacs-color-theme-solarized#179]
Hi, @sellout !

I've found that colors mismatch for Haskell sources, I didn't checked out other files and dark variant.  It seems that you're a bit busy, there are some other issues I'm facing with your theme.

Here is a screenshots
**Neovim**
![2016-01-28 21 33 27](https://cloud.githubusercontent.com/assets/744471/12652400/7cea5318-c60c-11e5-8c11-5f63e7a67764.png)

Your theme
![2016-01-28 9 36 45 pm](https://cloud.githubusercontent.com/assets/744471/12652413/8b9db846-c60c-11e5-9ccd-587f6e03b11c.png)

And a screenshot from Ethan Schoonover’s site
![Ethan Schoonover](http://ethanschoonover.com/solarized/img/screen-haskell-light.png)

**Comment by sellout** [comment]
So, I’m not saying it’s _not_ a bug, but you should read [this](https://github.com/sellout/emacs-color-theme-solarized/wiki/Why-doesn't-it-look-like-the-VIM-version%3F) first.

I’m going to close this, but feel free to ask me any questions about that link, and to reopen it if you find a place where the Emacs and Vim faces should be closer, that you think Solarized can control. Thanks.

**Comment by geraldus** [comment]
I agree and aware that Emacs have different syntax model than Vim.  What if I'll try to increase color match for haskell source files based on `haskell-mode` faces?

**Comment by sellout** [comment]
I think any improvement would be great. I actually have a project sellout/emacs-extended-faces that tries to both provide more fine-grained faces and minimize the number of faces a theme needs to define.

I have a local branch of solarized (which I should publish) that depends on that project.

Some of that may be useful to you as you dig deeper.

My guess, however, is that a lot of the Haskell buffer just uses the `default` face, and to fix that you’ll need to work on haskell-mode directly. Also, I think there are haskell modes that talk to GHC and get semantic information (EG, distinguishing whether something is a function or a variable), and those modes (I should know what they are, but don’t) might improve the highlighting without having to edit anything.

**Comment by geraldus** [comment]
I do work on `haskell-mode` directly :D  
There are for example, `haskell-keyword-face`, `haskell-definition-face` and other face which will help to make it better color matching.  I'll take a look at your extended faces repo.
