### ISSUE TITLE
In emacs 24 I cannot get load-theme to recognize solarized.

### ISSUE THREAD

**Issue by milkypostman** [sellout/emacs-color-theme-solarized#18]
I have the directory in my load path.  but load-theme (and even enable-theme) do not recognize the theme as being installed.

**Comment by hineios** [comment]
Have you considered including this on Melpa too?

(apparently Marmalade has an expired certificate, is [no longer ELPA compatible and is discontinued](https://www.emacswiki.org/emacs/MarmaladeRepo)?

**Comment by drewwells** [comment]
lol, i'm still seeing this issue. Do the install instructions need to include load-path? I don't see anything new that tells people how to get the el files included as part of load-path
