### ISSUE TITLE
Any plan to move from "color-theme" to "deftheme".

### ISSUE THREAD

**Issue by xarthurx** [sellout/emacs-color-theme-solarized#184]
Not an issue, actually.
Just want to ask if there is any plan to move this theme into the new emacs theme framework, since I like this theme so much.

**Comment by sellout** [comment]
It supports both. If you have Emacs 24 or newer, you should be following the instructions for that in the readme, rather than the instructions for older versions.

**Comment by sellout** [comment]
Feel free to reopen if that doesn’t answer your question.

**Comment by xarthurx** [comment]
Yes I saw the instruction.

The interesting part is if I delete the "color-theme" package in Emacs,
when starting Emacs again, it gave me errors.

On 19 February 2016 at 22:35, Greg Pfeil <notifications@github.com> wrote:

> Feel free to reopen if that doesn’t answer your question.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sellout/emacs-color-theme-solarized/issues/184#issuecomment-186499411>
> .
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by xarthurx** [comment]
Warning (emacs): Unable to activate package `color-theme-solarized'.
Required package `color-theme-6.5.5' is unavailable
Warning (initialization): An error occurred while loading
`/home/x__x/.emacs.d/init.el':

error: Unable to find theme file for `solarized'

On 20 February 2016 at 10:15, X <xliotx@gmail.com> wrote:

> Yes I saw the instruction.
>
> The interesting part is if I delete the "color-theme" package in Emacs,
> when starting Emacs again, it gave me errors.
>
> On 19 February 2016 at 22:35, Greg Pfeil <notifications@github.com> wrote:
>
>> Feel free to reopen if that doesn’t answer your question.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sellout/emacs-color-theme-solarized/issues/184#issuecomment-186499411>
>> .
>>
>
>
>
> --
> MA Zhao
>
> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*

**Comment by xarthurx** [comment]
Update:

this is because uninstalling color-theme will delete solarized theme from
"custom-theme-dictionary", and if I install the theme again, "color-theme"
was reinstalled.
It seems solarized theme depend on the "color-theme" package.

Sincerely,

On 20 February 2016 at 10:18, X <xliotx@gmail.com> wrote:

> Warning (emacs): Unable to activate package `color-theme-solarized'.
> Required package `color-theme-6.5.5' is unavailable
> Warning (initialization): An error occurred while loading
> `/home/x__x/.emacs.d/init.el':
>
> error: Unable to find theme file for `solarized'
>
> On 20 February 2016 at 10:15, X <xliotx@gmail.com> wrote:
>
>> Yes I saw the instruction.
>>
>> The interesting part is if I delete the "color-theme" package in Emacs,
>> when starting Emacs again, it gave me errors.
>>
>> On 19 February 2016 at 22:35, Greg Pfeil <notifications@github.com>
>> wrote:
>>
>>> Feel free to reopen if that doesn’t answer your question.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/sellout/emacs-color-theme-solarized/issues/184#issuecomment-186499411>
>>> .
>>>
>>
>>
>>
>> --
>> MA Zhao
>>
>> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>>
>
>
>
> --
> MA Zhao
>
> *"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
>



-- 
MA Zhao

*"SAVE PAPER - PLEASE THINK BEFORE YOU PRINT!"*
