### ISSUE TITLE
[How to]: reverse minibuffer prompt in iTerm2

### ISSUE THREAD

**Issue by srustamo** [sellout/emacs-color-theme-solarized#190]
Great theme. 

iTerm2 (its own theme set to Solarized, as advised in the readme here) minibuffer prompt looks like this:

<img width="387" alt="screen shot 2016-09-07 at 13 10 46" src="https://cloud.githubusercontent.com/assets/749813/18304716/6d0bf924-74fd-11e6-997c-72441cab1bc7.png">

GUI same theme looks like this:

<img width="417" alt="screen shot 2016-09-07 at 13 15 29" src="https://cloud.githubusercontent.com/assets/749813/18304723/7d398cbc-74fd-11e6-821c-b440ba0c209e.png">

Anyway to make the iTerm2 minibuffer prompt (which shows `M-x..`) to stand out more? Reverse, perhaps?

**Comment by ChrisWills** [comment]
Looks like you have "Brighten bold text" enabled. In iterm2 goto Preferences -> Profiles -> Colors and uncheck "Brighten bold text". 

A normal 16 color terminal colorscheme is 8 colors + 8 bright versions of the previous colors so this option is usually on by default. With Solarized, we are using the 16 color slots to form a 16color palette and the normal-bright relationship doesn't hold.

**Comment by srustamo** [comment]
Many thanks.
