### ISSUE TITLE
dark blue color hard on see

### ISSUE THREAD

**Issue by QikeLi** [sellout/emacs-color-theme-solarized#196]
Thank you for this awesome theme. I have been using it for a long time. I recently did a major re-configuration of my emacs and installed the latest version of the solarized theme. Now, some fonts are dark blue, which are hard to see. Would you please advise how to fix this issue? 

![image](https://cloud.githubusercontent.com/assets/6344366/21875189/68569fc2-d837-11e6-932b-437f13c4bac6.png)

**Comment by rchar01** [comment]
Hello,
please check what face (blue) is this.
You can use `M-x describe-face RET`, (second `RET` for details) to find out what face is applied to the text at point (under the cursor).

**Comment by QikeLi** [comment]
Thank you for the suggestions!
