### ISSUE TITLE
Emacsclient -c can not start 

### ISSUE THREAD

**Issue by favadi** [sellout/emacs-color-theme-solarized#58]
After  commit 6948f4f8b7, I cannot use emacsclient properly.

When I run emacsclient -c, I get 

```
Waiting for Emacs...
*ERROR*: Wrong type argument: stringp, nil
````

But everything run well with emacsclient -t.

In my init.el.

```Lisp
;; Color theme
(add-to-list 'load-path "~/.emacs.d/themes/solarized/")
(require 'color-theme)
(require 'color-theme-solarized)
(color-theme-solarized-dark)
(add-hook 'after-make-frame-functions
          '(lambda (f)
             (with-selected-frame f
               (when (window-system f) (color-theme-solarized-dark)))))
```

My emacs version is 23.4.1. 

Update:
> I add these lines in my init.el.
> 
> ```Lisp
> (setq debug-on-error t)
> ```
> 
> And I still get 
> 
> ```
> *ERROR*: Wrong type argument: stringp, nil
> ```
> Nothing more or less.
> 
> And if I start emacs normally (not with daemon-client) and run server-start, then emacsclient run well. 
> If you need more information, please let me know.

**Comment by sellout** [comment]
This problem no longer exists in the current version as we never call (display-color-cells) directly any more.
