### ISSUE TITLE
emacsclient in terminal completely unreadable.

### ISSUE THREAD

**Issue by vspinu** [sellout/emacs-color-theme-solarized#60]
Hi Greg,

Previously I was setting solarize-termcolors to 256 and I could use GUI emacs and emacsclient properly. Now I don't see this option anymore. When I run emacsclient (server being GUI) I am stuck with this screen

![Solarized terminal](http://vitalie.spinu.info/misc/solarized.png)

This is not with default terminal colours. But even if I set my xterm palet to solorised (which works for all other aplications) my emacsclient display is still unreadable. The key is that the color3 is used as a background.

Any ideas? Is there a way to use degraded termcolors now?

**Comment by ceyes** [comment]
Hello, I found a simple hook, which works for me.
Refer http://stackoverflow.com/questions/18904529/after-emacs-deamon-i-can-not-see-new-theme-in-emacsclient-frame-it-works-fr

```
(if (daemonp)
    (add-hook 'after-make-frame-functions
              (lambda (frame)
                (select-frame frame)
                (load-theme 'solarized-dark t)))
      (load-theme 'solarized-dark t))

```

**Comment by sellout** [comment]
The unified theme (`solarized` instead of `solarized-dark`/`solarized-light`) has now been merged into master. This should all behave much better now.
