### ISSUE TITLE
emacs -nw with Solarized Dark iTerm2 theme clobbers background colour

### ISSUE THREAD

**Issue by bradleywright** [sellout/emacs-color-theme-solarized#62]
![Shows background colour](http://s3.intranation.com.s3.amazonaws.com/screengrabs/solarized-dark.png)

Background isn't set to `nil`, so the colour of `#1c1c1c` (`base03`) shows through. `TERM` is `xterm-256color`, but I get varying behavioural issues with `xterm` as well.

**Comment by sellout** [comment]
This should be fixed in c677b269bb0c613e267ea27ab3154c7737cd6785.

**Comment by ceyes** [comment]
Thanks, latest version works perfect on my rxvt-unicode-256color.
