### ISSUE TITLE
@fmt-* in face definition makes faces unmerge-able

### ISSUE THREAD

**Issue by lewang** [sellout/emacs-color-theme-solarized#67]
There are a lot situations where multiple faces are applied to text.  For example `font-lock-keywords` takes a "prepend" and "append" option to manage the order of faces.

However faces which have "@fmt-*" in their definition don't work well with other faces.  For example @fmt-bold makes it impossible for another face to specify underline because it wipes it out.  

I'm checking the default themes that ship with Emacs24 and they don't do this.  Why was this design choice made?

**Comment by sellout** [comment]
I agree this isn’t ideal. This is how the Vim theme works and in some cases it’s intended. I haven’t yet managed to untangle the cases where you want to stomp on some face properties and the times when you want them to merge.

**Comment by sellout** [comment]
Ok, I’ve made it so the faces merge better.
