### ISSUE TITLE
Theme Color Mismatch

### ISSUE THREAD

**Issue by cfebs** [sellout/emacs-color-theme-solarized#71]
I have recently started to check out emacs, but I cannot seem to get solarized to work properly.  I have done a _ton_ of googling, but I cannot figure this out.

I am using:
- putty tray w/ ubuntu server running as a vm. Used the puttry tray solarized files to change the default terminal colors.
- screen
- emacs 23 and 24

I have been using the Vim themes for some time now without issue:

![vim](http://i.imgur.com/ZiAKL.png)

That's using the same putty setup and everything, looks perfect

But here is what my emacs looks like:

![emacs](http://i.imgur.com/OcPuR.png)

Both these are with the shell test file from the solarized repo.

Here is my day old .emacs file:  https://gist.github.com/3732955
- my `~/.emacs.d/src` folder contains `color-theme`, `emacs-color-theme-solarized` and `evil` all cloned from git repos.
- here is what `tty-dark` looks like:  http://i.imgur.com/frjXi.png   you can see that the reds and other colors are still picked up

*Emacs 24*

Following the instructions (add to custom load path, load theme), I arrive at the same exact screenshot as 23.

I can't figure out what I am missing.  It works well in vim so it must not be the terminal settings.  Is there some extra emacs config that I am missing?

Thank you for the help,

**Comment by sellout** [comment]
If `(display-color-cells)` returns 8, then you’re going to end up with a very limited color palette. To fix that, try setting `TERM=xterm-256color`, which should also attempt to use exact colors as of c677b269bb0c613e267ea27ab3154c7737cd6785.
