### ISSUE TITLE
solarized themes not working on Mountain Lion

### ISSUE THREAD

**Issue by arunabha** [sellout/emacs-color-theme-solarized#76]
I'm using [Emacs 24 for Mountain Lion] (https://github.com/xajler/emacs24-macosx-lion-fullscreen)

The solarized themes are available in load-themes, but selecting any solarized theme results in the following error.

'Symbol's function definition is void: find-color'. My .emacs is pretty bare

(add-to-list 'custom-theme-load-path "path-to/emacs-color-theme-solarized")
(transient-mark-mode 't)

Any ideas on how to fix

**Comment by sellout** [comment]
The new version no longer has a `find-color` function … hopefully that will avoid the issue.
