### ISSUE TITLE
Solarized breaks "customize-theme"

### ISSUE THREAD

**Issue by zilti** [sellout/emacs-color-theme-solarized#92]
I installed "solarized" using packages and the marmalade repo.
After installation the theme immediately switches to solarized-light.
"customize-theme" shows 3 themes, Solarized (which is broken) and Solarized-light and Solarized-dark. I can select either the light or dark one and save the setting, but after restarting, Emacs starts with no theme at all.

**Comment by sellout** [comment]
The marmalade version is very old. Also, I have just today merged a big overhaul. I think this issue is fixed now, but please reopen if that is not the case for you. Thanks.
